export const pageTypes = {
  AUTH: 'AUTH',
  CONTACTS: 'CONTACTS',
  PROFILE: 'PROFILE',
  CHATS: 'CHATS',
  MESSAGES: 'MESSAGES'
};
export const actionTypes = {
  GO_TO_CONTACTS_PAGE: 'GO_TO_CONTACTS_PAGE',
  GO_TO_CHATS_PAGE: 'GO_TO_CHAT_PAGE',
  GO_TO_PROFILE_PAGE: 'GO_TO_USER_PROFILE_PAGE',
  GO_TO_AUTH_PAGE: 'GO_TO_AUTH_PAGE',
  GO_TO_MESSAGES_PAGE: 'GO_TO_MESSAGES_PAGE'
};
